//
//  GitInfo.swift
//  CCTray
//
//  Created by Robert Goniszewski on 14/07/2025.
//  Auto-generated by build script - do not edit manually
//

import Foundation

struct GitInfo {
    static let repositoryURL = "https://github.com/goniszewski/cctray"
    static let authorHandle = "@goniszewski"
    static let authorName = "Robert Goniszewski"
    
    // Auto-updated by build script
    static let commitHash = "2702aa31111dee82952e10fc48908d5f49db9647"
    static let commitDate = "2025-07-14 17:06:47 +0200"
    static let shortCommitHash = "2702aa3"
    
    static var formattedCommitDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss Z"
        
        if let date = formatter.date(from: commitDate) {
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
            return formatter.string(from: date)
        }
        
        return commitDate
    }
    
    static var repositoryDisplayURL: String {
        return repositoryURL.replacingOccurrences(of: "https://", with: "")
    }
}